POST http://localhost:8080/users
Content-Type: application/json

{
"userName": "Spring Security",
"password": "learnSpringSecurity",
"firstName": "Security",
"lastName": "Spring",
"localDate": "2019-09-17"
}